config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'home', to: 'home#index'
  end
  namespace :backoffice do
    get 'dashboard', to: 'dashboard#index'
  end
  devise_for :admins
  devise_for :members

  root 'site/home#index'
end

app/models/ad.rb
class Ad < ApplicationRecord
    monetize :price_cents
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < ApplicationController
  layout "backoffice"
  def index
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  before_action :authenticate_member!
  
  layout "site"
  
  def index
    @categories = Category.all
    @ads = Ad.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/backoffice/dashboard/index.html.erb
    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">Dashboard</a>
          </li>
          <li class="breadcrumb-item active">Blank Page</li>
        </ol>

        <!-- Page Content -->
        <h1>Blank Page</h1>
        <hr>
        <p>This is a great starting point for new custom pages.</p>

      </div>
      <!-- /.container-fluid -->

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minionsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin - Blank Page</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>

</head>

<body>
  <div id="id="wrapper""
    <%= render partial: "layouts/backoffice_shared/navigation" %>
    <%= yield %>
    <%= render partial: "layouts/backoffice_shared/footer" %>    
  </div>
</body>

</html>

app/views/layouts/backoffice_shared/_footer.html.erb
    <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Your Website 2019</span>
          </div>
        </div>
      </footer>

app/views/layouts/backoffice_shared/_navigation.html.erb
  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">Start Bootstrap</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="index.html">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Login Screens:</h6>
          <a class="dropdown-item" href="login.html">Login</a>
          <a class="dropdown-item" href="register.html">Register</a>
          <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Other Pages:</h6>
          <a class="dropdown-item" href="404.html">404 Page</a>
          <a class="dropdown-item active" href="blank.html">Blank Page</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>
    </ul>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>MinionsApp</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track': 'true' %>    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'site', 'data-turbolinks-track': 'true' %>
    
    <%= csrf_meta_tags %>

</head>

<body>
  <%= render partial: "layouts/site_shared/navigation" %>
  <%= yield %>
  <%= render partial: "layouts/site_shared/footer" %>
</body>

</html>

app/views/layouts/site_shared/_footer.html.erb
    <div class="container">
      <hr>
      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; MinionsApp 2019</p>
          </div>
        </div>
      </footer>  
    </div>

app/views/layouts/site_shared/_navigation.html.erb
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navegation">
    <div class="container">
      <div class="navbar-header">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"></a>
      </div>
      
      <div class="collapse navbar-collapse" id="bs-exemple-navbar-collapse-1">
        <ul class="nav navbar-nav">  
          <li>
            <a href="#">About</a>
          </li>
          <li>
            <a href="#">Services</a>
          </li>          
          <li>
            <a href="#">Contact</a>
          </li>                    
        </ul>
      </div>
    </div>
  </nav>

app/views/members/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/site/home/index.html.erb
  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-md-3">

        <p class="lead">Categorias</p>
        <div class="list-group">
          <% @categories.each do |category| %>
          <a href="#" class="list-group-item"><%= category.description %></a>
          <% end %>        
        </div>
        <br>
        <h5>Usuário logado:</h5>
        <h4><%= current_member.email %></h4>
        <h6>(by email)</h6>      
      </div>

      <div class="col-md-9">

        <div class="row carousel-holder">
          <div class="col-md-12"
            <div id="carousel-exemple-generic" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carousel-exemplexample-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-exemple-generic" data-slide-to="1"></li>
                <li data-target="#carousel-exemple-generic" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner" src="http://placehold.it/800x300" alt="">
              <div class="carousel-inner" src="http://placehold.it/800x300" alt="">     
              <div class="carousel-inner" src="http://placehold.it/800x300" alt="">     
            </div>
            <a class="left carousel-control" href="#carousel-exemple-generic" data-slide="prev">
              <spam class="glyphicon glyphicon-chevron-left"></spam>
            </a>  
            <a class="left carousel-control" href="#carousel-exemple-generic" data-slide="next">            
              <spam class="glyphicon glyphicon-chevron-right"></spam>             
            </a>
          </div>
        </div>
      
        <div class="row">
          <p></p><p></p>
          <div class="col-sm-4 col-lg-6 col-mb-4">
            <div class="thumbnail">
              <img src="<% @ads.each do |ad| %><%= ad.img %><% end %>" alt="">
              <div class="caption">
                <h4 class="pull-right">R$<% @ads.each do |ad| %><%= ad.price_cents %><% end %></h4>
                <h4><a href="#"><% @ads.each do |ad| %><%= ad.title %><% end %></a></h4>
                <p><% @ads.each do |ad| %><%= ad.description %><% end %></p>
              </div>  
              <div class="ratings">
                <a target="_blank" href="http://bootsnipp.com"/>Reservar</a><p class="pull-right"><% @ads.each do |ad| %><%= ad.views %><% end %></p>
                <p>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>                  
                  <span class="glyphicon glyphicon-star"></span>                  
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                </p>
              </div>
            </div>
          </div>  
          <div class="col-sm-4 col-lg-6 col-mb-4">
            <div class="thumbnail">
              <img src="http://i64.tinypic.com/1zxmpab.png" alt="">
              <div class="caption">
                <h4 class="pull-right">R$24.99</h4>
                <h4><a href="#">Smurf</a></h4>
                <p>Smurf fofo</p>
              </div>  
              <div class="ratings">
                 <a target="_blank" href="http://bootsnipp.com"/>Reservar</a><p class="pull-right">86 Views</p>
                <p>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>                  
                  <span class="glyphicon glyphicon-star"></span>                  
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                </p>
              </div>
            </div>
          </div> 
          <div class="col-sm-4 col-lg-6 col-mb-4">
            <div class="thumbnail">
              <img src="http://i67.tinypic.com/oprait.jpg" alt="">
              <div class="caption">
                <h4 class="pull-right">R$56.99</h4>
                <h4><a href="#">Boo</a></h4>
                <p>Menina do Monstros SA</p>
              </div>  
              <div class="ratings">
                <a target="_blank" href="http://bootsnipp.com"/>Reservar</a><p class="pull-right">35 Views</p>
                <p>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>                  
                  <span class="glyphicon glyphicon-star"></span>                  
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                </p>
              </div>
            </div>
          </div>  
          <div class="col-sm-4 col-lg-6 col-mb-4">
            <div class="thumbnail">
              <img src="http://i68.tinypic.com/255utd5.jpg" alt="">
              <div class="caption">
                <h4 class="pull-right">R$22.99</h4>
                <h4><a href="#">Buzz Lightyear</a></h4>
                <p>Herói de Toy Story. </p>
              </div>  
              <div class="ratings">
                <a target="_blank" href="http://bootsnipp.com"/>Reservar</a><p class="pull-right">61 Views</p>
                <p>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>                  
                  <span class="glyphicon glyphicon-star"></span>                  
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                </p>
              </div>
            </div>
          </div>  
          
        </div>
      </div>
    </div>
  </div>  